### ISSUE TITLE
Using direnv for a Ruby environment, Bundler fails to load rake

### ISSUE THREAD

**Issue by sandstrom** [bridgetownrb/bridgetown#608]
**Bridgetown Version**:
1.1.0

**To Reproduce**

I've added a repo which should be sufficient to reproduce this error:
https://github.com/sandstrom/bridgetown-bug-repro1

But basically the steps are:

1. Install direnv and configure it for ruby (see .envrc file in repro repo).
2. Install bridgetown.
3. Run `bin/bridgetown start`.

**Current behavior**

```
% bin/bridgetown start
[Bridgetown]           Starting: Bridgetown v1.1.0 (codename "Belmont")
[Server] * Puma version: 5.6.4 (ruby 2.7.1-p83) ("Birdie's Version")
[Server] * PID: 72181
[Server] * Listening on http://0.0.0.0:4000
[Server] Use Ctrl-C to stop
[Frontend] bundler: failed to load command: bridgetown (/Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/bin/bridgetown)
[Frontend] LoadError: cannot load such file -- rake
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/bridgetown-core-1.1.0/lib/bridgetown-core/commands/base.rb:48:in `require'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/bridgetown-core-1.1.0/lib/bridgetown-core/commands/base.rb:48:in `handle_no_command_error'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/thor-1.2.1/lib/thor/command.rb:31:in `run'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/thor-1.2.1/lib/thor/command.rb:135:in `run'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/gems/bridgetown-core-1.1.0/bin/bridgetown:38:in `<top (required)>'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/bin/bridgetown:23:in `load'
[Frontend]   /Users/my-user/repos/my-org/bridgetown-bug-repro1/.direnv/ruby/bin/bridgetown:23:in `<top (required)>'
[Bridgetown]        Environment: development
[Bridgetown]             Source: /Users/my-user/repos/my-org/bridgetown-bug-repro1/src
[Bridgetown]        Destination: /Users/my-user/repos/my-org/bridgetown-bug-repro1/output
[Bridgetown]     Custom Plugins: /Users/my-user/repos/my-org/bridgetown-bug-repro1/plugins
[Bridgetown]         Generating… 
[Bridgetown]         Pagination: disabled. Enable in site config with pagination:\n enabled: true
[Bridgetown]            esbuild: There was an error parsing your esbuild manifest file. Please check your esbuild manifest file for any errors.
[Bridgetown]             Done! 🎉 Completed in less than 0.18 seconds.
[Bridgetown]                     
[Bridgetown]     Now serving at: http://localhost:4000
[Bridgetown]                     http://192.168.65.2:4000
[Bridgetown]                     

```

**Expected behavior**

Frontend should run.

**Workaround fix**

It works if I remove the characters `bundle exec ` from this line:

https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/tasks/bridgetown_tasks.rake#L15

**Thoughts**

Is the bundle exec prefix really needed here? For us it's fine to omit it, but not sure if that goes for everyone.

**Computing environment (please complete the following information):**
 - OS: macOS 12.3
 - Ruby Version: 2.7

**Comment by jaredcwhite** [comment]
I'll try to dig into this soon…hadn't heard of direnv to be honest, and I should mention our recommended installation approach is to use rbenv.

**Comment by sandstrom** [comment]
Sounds great! 

As mentioned above, maybe we can just skip the `bundle exec ` prefix?

But if some scenarios need it, then a command line flag or config value may be better. For example it could be `frontend-runner-prefix` or similar. Which one could then set to nothing to clear it. Or replace with something other than `bundle exec`, if needed.

**Comment by sandstrom** [comment]
@jaredcwhite Sorry for persistent asking, but just wanted to see if you have any thoughts on this?

We're closing in on our middleman -> bridgetown migration, and this is one of the blockers (we have a manual hack in place now, via a private fork).

As mentioned above, to me it seems like it should be fine to simply drop the `bundle exec` prefix. Since the outer invocation would already be running via `bundle exec`, any inner child-process invocation should inherit env etc from the parent process.

**Comment by zealot128** [comment]
Had the same issue (but using asdf version manager), but just updating to Ruby 3.0.x seemed to have fixed the issue with my environment .

**Comment by sandstrom** [comment]
@zealot128 Thanks, we'll try it out and see if that solves it under our scenario too.

**Comment by sandstrom** [comment]
Sounds great!

**Comment by davidstosik** [comment]
I have a similar issue which did not get fixed after I removed `bundle exec` from this line:
https://github.com/bridgetownrb/bridgetown/blob/f163ea77918c1019a5b4e55d85293a64abfb79b5/bridgetown-core/lib/bridgetown-core/tasks/bridgetown_tasks.rake#L15

<details>
<summary>Here is the error I'm getting when I run <code>bridgetown --help</code>.</summary>

```
bridgetown --help
Bridgetown v1.1.0 "Belmont" is a Webpack-aware, Ruby-powered static site generator for the modern Jamstack era

Usage:
  bridgetown <command> [options]

Commands:
  bridgetown apply                    # Applies an automation to the current site
  bridgetown build                    # Build your site and save to destination folder
  bridgetown clean                    # Clean the site (removes site output and metada...
  bridgetown configure CONFIGURATION  # Set up bundled Bridgetown configurations
  bridgetown console                  # Invoke an IRB console with the site loaded
  bridgetown dev                      # Alias of start
  bridgetown doctor                   # Search site and print specific deprecation war...
  bridgetown dream                    # There's a place where that idea still exists a...
  bridgetown esbuild ACTION           # Perform actions on the Bridgetown esbuild conf...
  bridgetown help <command>           # Show detailed command usage information and exit
  bridgetown new PATH                 # Creates a new Bridgetown site scaffold in PATH
  bridgetown plugins <command>        # List installed plugins or access plugin content
  bridgetown serve                    # DEPRECATED (Serve your site locally using WEBr...
  bridgetown start                    # Start the Puma server, frontend bundler, and B...
  bridgetown webpack ACTION           # Perform actions on the Bridgetown Webpack conf...

/Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bridgetown-core-1.1.0/lib/bridgetown-core/commands/base.rb:97:in `require': cannot load such file -- rake (LoadError)
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bridgetown-core-1.1.0/lib/bridgetown-core/commands/base.rb:97:in `help'
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /Users/sto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bridgetown-core-1.1.0/bin/bridgetown:38:in `<top (required)>'
        from /Users/sto/.rbenv/versions/3.1.2/bin/bridgetown:25:in `load'
        from /Users/sto/.rbenv/versions/3.1.2/bin/bridgetown:25:in `<main>'
```

</details>

I use rbenv to manage Ruby versions, and here's what one can do to reproduce:

```
mkdir /tmp/repro
cd /tmp/repro
rbenv local 3.1.2 # creates .ruby-version
bundle init # creates Gemfile
gem install bridgetown # installs Bridgetown in Ruby 3.1.2's gems
bridgetown --help # triggers the error above
```

Now if I remove the `Gemfile` from the directory, the command does not fail anymore.
Because I did not run `bridgetown` with the `bundle exe` prefix, the presence (or absence) of a `Gemfile` should not be impacting the command, as far as I know.

**Comment by sandstrom** [comment]
Fixed in https://github.com/bridgetownrb/bridgetown/pull/641
