### ISSUE TITLE
Missing name gsubs when creating a new plugin with bridgetown-1.2.0.beta4

### ISSUE THREAD

**Issue by svoop** [bridgetownrb/bridgetown#670]
```
% bridgetown plugins new bridgetown-credentials

         run  git clone -b v1.2-initializer https://github.com/bridgetownrb/bridgetown-sample-plugin bridgetown-credentials from "."
Cloning into 'bridgetown-credentials'...
remote: Enumerating objects: 223, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 223 (delta 89), reused 143 (delta 35), pack-reused 0
Receiving objects: 100% (223/223), 840.49 KiB | 8.94 MiB/s, done.
Resolving deltas: 100% (89/89), done.
         run  rm -rf .git from "./bridgetown-credentials"
         run  git init from "./bridgetown-credentials"
Initialized empty Git repository in /Users/svoop/Development/ofm/web/bridgetown-credentials/.git/
        gsub  bridgetown-credentials/bridgetown-credentials.gemspec
        gsub  bridgetown-credentials/bridgetown-credentials.gemspec
        gsub  bridgetown-credentials/bridgetown-credentials.gemspec
        gsub  bridgetown-credentials/bridgetown-credentials.gemspec
        gsub  bridgetown-credentials/package.json
        gsub  bridgetown-credentials/package.json
        gsub  bridgetown-credentials/lib/bridgetown-credentials.rb
  Exception raised: Errno::ENOENT
No such file or directory @ rb_sysopen - /Users/svoop/Development/ofm/web/bridgetown-credentials/lib/bridgetown-credentials.rb
                 1: /Users/svoop/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor/actions/file_manipulation.rb:274:in `binread'
                 2: /Users/svoop/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor/actions/file_manipulation.rb:274:in `gsub_file'
                 3: /Users/svoop/.gem/ruby/3.1.0/gems/bridgetown-core-1.2.0.beta4/lib/bridgetown-core/commands/plugins.rb:202:in `block in new'
                 4: /Users/svoop/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor/actions.rb:190:in `block in inside'
                 5: /Users/svoop/.rubies/ruby-3.1.3/lib/ruby/3.1.0/fileutils.rb:139:in `chdir'
         Backtrace: Use the --trace option for complete information.
```

**Bridgetown Version**:
1.2.0.beta4

**Computing environment (please complete the following information):**
 - OS: macOS 13.1 ARM
 - Ruby Version: 3.1.3

**Comment by svoop** [comment]
Apparently, it's the dash in `bridgetown-credentials`. Works on 1.1 though.

**Comment by svoop** [comment]
Some minor issues with the generated plugin: There are still occurrences of "sample plugin" which are not gsubbed:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/7255/208130474-6d7b077f-0d37-4316-a42f-e9457c9d9015.png">

**Comment by rickychilcott** [comment]
Still seeing this in beta5. Just thought I'd note it.

**Comment by jaredcwhite** [comment]
Should be resolved now in the final release.

**Comment by svoop** [comment]
Great, thanks @jaredcwhite 🎉
