### ISSUE TITLE
Pagination and multi locales 

### ISSUE THREAD

**Issue by jclusso** [bridgetownrb/bridgetown#789]
When using pagination with `locales: multi`, I've run into the following error.

```
NoMethodError: undefined method `parent' for "blog/index.slim":String
/Users/jarrett/Projects/random/bridgetown/bridgetown-core/lib/bridgetown-core/concerns/localizable.rb:16:in `block in all_locales'
/Users/jarrett/Projects/random/bridgetown/bridgetown-core/lib/bridgetown-core/concerns/localizable.rb:15:in `select'
```

When digging further into this I realized that the `all_locales` method in Localizable tries to call `parent` on `relative_path`. When the `result_set` is a `Bridgetown::Resource::Base`, that works fine since it returns a `Pathname` object. When it is a `Bridgetown::GeneratedPage`, `relative_path` returns a `String` which breaks.

Now I'm not sure if the issue lies within `relative_path` because I'd assume a lot of other stuff would be broken if that wasn't supposed to return a String in this situation. Here is what I did to try and fix this.

```ruby
# frozen_string_literal: true

module Bridgetown
  module Localizable
    def all_locales
      result_set = case self
                   when Bridgetown::Resource::Base
                     collection.resources
                   when Bridgetown::GeneratedPage
                     site.generated_pages
                   else
                     []
                   end

      matching_resources = result_set.select do |item|
        if item.relative_path.is_a?(String)
          item.localeless_path == localeless_path
        else
          item.relative_path.parent == relative_path.parent
        end && item.data.slug == data.slug
      end

      matching_resources.sort_by do |item|
        site.config.available_locales.index item.data.locale
      end
    end

    def localeless_path
      relative_path.gsub("#{data.locale}/", '')
    end

  end
end
```

Now this worked fine for fixing the error and generating the proper pages. The problem that I still face is that the pages for anything, but my base locale are not returning anything when calling `in_locale(paginator.resources)`.

I'm not sure if I'm going down the wrong path trying to fix this so I figured it's time to open an issue. I also wasn't sure if this is related to #711.

**Bridgetown Version**: 1.3.0 "Kelly Butte"

**To Reproduce**
- Dynamically generate a resource using a builder and add_resource
- Make a page like `blog.erb` that defines `locale: multi` and `locales: ["en", "es"]`
- Enable pagination

**Comment by jclusso** [comment]
I realized that this fix actually works if I don't wrap `paginator.resources` with `in_locale`.
